/**
 * particle engine dev
 * API interface for \'particle engine dev\'
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstanceGet200Response { 
    /**
     * Directory on which this \'particle engine dev\' instance is running
     */
    componentDirectory?: string;
    /**
     * PID of the this \'particle engine dev\' instance.
     */
    pid?: number;
}

