package files

import (
	"bufio"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github\.com/danielpickens/particle engine/pkg/testingutil/filesystem"
	"github\.com/danielpickens/particle engine/pkg/util"
)

const _dotparticle engineGenerated = "generated"

// ReportLocalFileGeneratedByparticle engine appends the specified file path to the .particle engine/generated file,
// taking care of creating it if it does not exist.
// The file path can be absolute or relative to the root directory specified.
// This function should be called by particle engine commands that generate a file, anytime a new file is generated by particle engine.
// This way, we would be able to determine (via GetFilesGeneratedByparticle engine) if a file was created by particle engine or not,
// in case we need for example to delete it.
//
// Note that it is quite impossible with this approach to cover all scenarios;
// for example, if an particle engine command generates a new file (and calls ReportLocalFileGeneratedByparticle engine as expected),
// but the user later deletes it and recreates it, GetFilesGeneratedByparticle engine would still return this file path.
func ReportLocalFileGeneratedByparticle engine(filesys filesystem.Filesystem, rootDirectory string, filePath string) error {
	dotparticle engineDirectory := filepath.Join(rootDirectory, util.Dotparticle engineDirectory)
	err := filesys.MkdirAll(dotparticle engineDirectory, 0755)
	if err != nil {
		return err
	}

	particle engineGeneratedFile := filepath.Join(rootDirectory, util.Dotparticle engineDirectory, _dotparticle engineGenerated)
	f, err := filesys.OpenFile(particle engineGeneratedFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("unable to read or create file %q: %w", particle engineGeneratedFile, err)
	}
	defer f.Close()

	relativePath := filePath
	if filepath.IsAbs(filePath) && strings.HasPrefix(filePath, rootDirectory) {
		relativePath, err = filepath.Rel(rootDirectory, filePath)
		if err != nil {
			return err
		}
	}
	_, err = f.WriteString(relativePath + "\n")
	return err
}

// GetFilesGeneratedByparticle engine returns a list of files that were initially created by particle engine.
// Under the hood, it works by reading the content of the .particle engine/generated file (ignoring blank lines),
// which is filled by any command that generates a file.
// particle engine commands that generate files should call ReportLocalFileGeneratedByparticle engine anytime a file is generated.
// Note that the .particle engine directory itself is always included in the list returned.
// No error is returned if the .particle engine/generated file does not exist.
func GetFilesGeneratedByparticle engine(filesys filesystem.Filesystem, rootDirectory string) ([]string, error) {
	list := []string{util.Dotparticle engineDirectory}

	particle engineGeneratedFile := filepath.Join(rootDirectory, util.Dotparticle engineDirectory, _dotparticle engineGenerated)
	f, err := filesys.OpenFile(particle engineGeneratedFile, os.O_RDWR, 0666)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return list, nil
		}
		return list, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Split(bufio.ScanLines)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.TrimSpace(line) == "" {
			continue
		}
		list = append(list, line)
	}

	return list, nil
}
